Phase no 1: Data Understanding

- Importing libraries

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

- Loading Dataset

In [16]:
dataset = pd.read_csv('customer_dataset.csv')

- checking top 2 rows of dataset

In [17]:
dataset.head(2)

,Customer ID,Age,Gender,City,Subscription Type,Monthly Spending,Tenure,Number of Purchases,Customer Support Requests,Login Frequency,Last Activity Date,Satisfaction Score,Churn Status
0,CUST-1001,58,Male,New York,Premium,92.00,15,2,3,Daily,2026-03-26,1,1
1,CUST-1002,20,Male,Los Angeles,Basic,14.65,39,1,0,Weekly,2026-03-29,5,1

- checking bottom 2 rows of dataset

In [18]:
dataset.tail(2)

,Customer ID,Age,Gender,City,Subscription Type,Monthly Spending,Tenure,Number of Purchases,Customer Support Requests,Login Frequency,Last Activity Date,Satisfaction Score,Churn Status
1498,CUST-2499,43,Male,Philadelphia,Premium,136.89,3,2,0,Bi-weekly,2026-04-09,2,0
1499,CUST-2500,21,Other,Chicago,Standard,32.56,5,1,2,Weekly,2026-06-07,3,0

- Checking null values in dataset if any

In [19]:
dataset.isnull().sum()

Customer ID                  0
Age                          0
Gender                       0
City                         0
Subscription Type            0
Monthly Spending             0
Tenure                       0
Number of Purchases          0
Customer Support Requests    0
Login Frequency              0
Last Activity Date           0
Satisfaction Score           0
Churn Status                 0
dtype: int64

- Checking duplicates in dataset and removing if any

In [20]:
print(f"The duplicates in the dataset is: {dataset.duplicated().sum()}")

The duplicates in the dataset is: 0

- Checking outliers in dataset

In [21]:
target_column = 'Churn Status'

q1 = dataset['Churn Status'].quantile(0.25)
q3 = dataset['Churn Status'].quantile(0.75)

iqr = q3-q1

lower_limit = q1 - (1.5 *iqr)
higher_limit = q3 + (1.5 *iqr)

outliers = dataset[(dataset[target_column]<lower_limit)| (dataset[target_column]>higher_limit)]
print(f'Total outlier in the {target_column} is: {len(outliers)}')

Total outlier in the Churn Status is: 338

- Encode categorical variables

In [28]:
# Remove the unique ID column because it is not a useful feature for modeling
dataset = dataset.drop(columns=['Customer ID'])

# Convert date column properly
dataset['Last Activity Date'] = pd.to_datetime(dataset['Last Activity Date'])

# One-hot encode categorical columns
categorical_cols = dataset.select_dtypes(include=['object']).columns.tolist()
dataset = pd.get_dummies(dataset, columns=categorical_cols, drop_first=True)

dataset.head()

,Age,Monthly Spending,Tenure,Number of Purchases,Customer Support Requests,Last Activity Date,Satisfaction Score,Churn Status,Categorical_col,Categorical_login,...,City_Philadelphia,City_Phoenix,City_San Antonio,City_San Diego,City_San Jose,Subscription Type_Premium,Subscription Type_Standard,Login Frequency_Daily,Login Frequency_Monthly,Login Frequency_Weekly
0,58,92.00,15,2,3,2026-03-26,1,1,1,1,...,False,False,False,False,False,True,False,True,False,False
1,20,14.65,39,1,0,2026-03-29,5,1,3,3,...,False,False,False,False,False,False,False,False,False,True
2,55,23.96,22,5,0,2026-05-24,4,0,3,3,...,False,False,False,False,False,False,False,False,False,True
3,42,54.15,52,2,0,2026-04-13,2,0,2,2,...,True,False,False,False,False,False,True,False,True,False
4,42,63.18,40,12,3,2026-03-22,1,1,3,3,...,False,False,False,False,False,False,True,False,False,True